version: '3'

services:
  home:
    image: docker.io/nginx:latest
    volumes:
      - ./home:/usr/share/nginx/html:z
      - ./conf.d:/etc/nginx/conf.d:z
      - ./images:/data/images:z
      - ./fonts:/data/fonts:z
    ports:
      - 5000:80
